version: '3'

services:
  web:
    image: dmytrolopushanskyy/ucuddle-crawlers:web
    restart: always
    build: ./web
    ports:
      - "8005:8000"
    env_file:
      - shared_vars.env
    #command: uvicorn app:app
    command: gunicorn --worker-class gevent --worker-connections 1000 --workers 3 --timeout 90 --log-level debug -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 app:app
  nginx:
    image: dmytrolopushanskyy/ucuddle-crawlers:nginx
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "5007:80"
    links:
      - web:web
    depends_on:
      - web
#  task-manager:
#    image: dmytrolopushanskyy/ucuddle-crawlers:task-manager
#    restart: always
#    build: ./task-manager
#    ports:
#      - "5010:5000"
#    env_file:
#      - shared_vars.env
#    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
#    elasticsearch:
#      image: "elasticsearch:7.11.1"
#      restart: always
#      volumes:
#        - ./ES_DATA:/usr/share/elasticsearch/data
#      environment:
#        - discovery.type=single-node
#        - bootstrap.memory_lock=true
#        - logger.level=WARN
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      ports:
#        - "9205:9200"
#  crawler:
#    image: dmytrolopushanskyy/ucuddle-crawlers:crawler
#    build: ./crawler
#    volumes:
#      - ./crawler:/crawler
#    env_file:
#      - shared_vars.env
#    depends_on:
#      - task-manager